### ISSUE TITLE
Autologin doesn't seem to quite work

### ISSUE THREAD

**Issue by Discomanco** [gorilla-devs/GDLauncher#256]
**Describe the bug**
During the last update, you `fixed the login token`, however now I'm getting logged in, without logging in. It's logged in as "no user". I can boot up Minecraft just fine, but is not able to join any server, due to Invalid Session, or Invalid Username (forgot the exact error)

**To Reproduce**
- Log in
- Shut down GDLauncher (PC restart may be required, maybe even overnight?)
- Start up GDLauncher, and have it auto 'login'
- No username has appeared, and no server can be joined

**Expected behavior**
To either log me out, or have my user log in again

**Possible solutions**
I have not tried reinstalling, or clearing any caches of sorts

**Screenshots**
![image](https://user-images.githubusercontent.com/4707702/67157254-fcae4980-f329-11e9-8548-c861348e4593.png)

**Operating System:**
 - OS: Win10

**Comment by blarfoon** [comment]
Can you try logging out and in again?

**Comment by Discomanco** [comment]
Logging out and in again makes you be logged in, but this happened twice (both after starting up the client for the day since the last launcher update)

**Comment by Midnex** [comment]
Really like to see this fixed, it is causing problems with inventory for single player. When i notice I am not logged in, it creates a player called undefined. But saves it to over my UUID for my player. When I log back in and enter the game I have the items the player undefined had, and lose all of my items i had. This has cost me so much gear due to the player undefined overwriting it.

This only happens when i use GDLauncher. And has happened a few dozen times. For a week until I found this I was simply logging out with nothing on me. Now I have switched back to Curse till this is fixed.

**Comment by kamild1996** [comment]
+1, this is quite an annoyance. Not as much as it could be thanks to the re-login functionality in modpacks, but still, having to randomly log back in again is not fun.

**Comment by 4rz0** [comment]
Still happening, if there's something I can do to help, please mention.

**Comment by TheDeviantCrafter** [comment]
As a temporary fix, would it be possible to add a warning if someone attempts to launch a pack while not logged in?

**Comment by Archilyte** [comment]
for now, i fixed it by unchecking remember me at login
