### ISSUE TITLE
[Bug] GD Icon doesnt show

### ISSUE THREAD

**Issue by furtabs** [gorilla-devs/GDLauncher#411]
**Operating System used:**
Arch

**Actual behavior:**
Show the GDLauncher Icon

**Steps to reproduce the behavior:**
Open the Launcher?

**Expected behavior:**
Show the GD Icon

**If applicable, add screenshots/videos to help explain:**
![image](https://user-images.githubusercontent.com/48419040/77971822-b63c1e00-72bd-11ea-9ffe-a5de167ee395.png)

**Comment by furtabs** [comment]
It’s fixed in the AUR package so I think it’s an issue with AppImages since the icons and normally pathed through the .desktop

**Comment by ghost** [comment]
Can you explain the issue further, can't say I understand.

**Comment by pkkid** [comment]
I'm hitting this same issue on Ubuntu 20.04. When starting the AppImage, there is no icon displayed for the running application. It's just an empty space. I tried using Alacarte to make a menu item containing an icon, but the running app still shows up with no icon in the Gnome Shell task manager. This is most likely due to the AppImage itself missing or not properly specifying which icon to display.

![2021-03-24 - missing icon](https://user-images.githubusercontent.com/435619/112362067-6b739d00-8caa-11eb-94f0-783720e6f670.png)

**EDIT:** Looking further, it seems this may be an issue with the AppImage project itself, and not a specific problem to GDLauncher. See upstream issue: https://github.com/AppImage/AppImageKit/issues/346. tldr: AppImages work well, but do not integrate well with various Linux environments as it needs a bit more maturity.

**Comment by AshtakaOOf** [comment]
to solve this issue just download gdlauncher.png and put it to these folder

**opt/GDLauncher/gdlauncher.png
usr/share/pixmaps/gdlauncher.png**

> to access these folder you will need to be admin

after this it should be fixed

![gdlauncher](https://user-images.githubusercontent.com/66513643/112387891-a3063780-8cf2-11eb-8f36-63051dd9d253.png)

> if you want to put the image using nautilus the default file manager in ubuntu go in a command line and type "sudo nautilus"

**Comment by pm065** [comment]
This happens in the .deb too:

(It's also marked as proprietary when it shouldn't be)

![image](https://user-images.githubusercontent.com/81559564/126288996-4073eb62-2bce-4842-846f-dbb81719f19a.png)

**Comment by AshtakaOOf** [comment]
> This happens in the .deb too:
> 
> (It's also marked as proprietary when it shouldn't be)
> 
> ![image](https://user-images.githubusercontent.com/81559564/126288996-4073eb62-2bce-4842-846f-dbb81719f19a.png)

I gived the solution so just do it if you want the logo

**Comment by pm065** [comment]
> I gived the solution so just do it if you want the logo

Yep, I did, just making sure the devs are aware this is an issue in both versions :)

**Comment by AshtakaOOf** [comment]
They know but it’s not something important to do

**Comment by huantianad** [comment]
Hey, just checking, does the AppImage still not have an icon in the taskbar? I've tested on my system (KDE Plasma), and it seems to work.
